/*!CK:3117804174!*//*1457450175,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["FnpSU"]); }

__d('StarsInput.react',['cx','fbt','React','TooltipLink.react'],function a(b,c,d,e,f,g,h,i){if(c.__markCompiled)c.__markCompiled();var j=c('React').PropTypes,k=c('React').createClass({displayName:'StarsInput',propTypes:{allowMultipleSubmissions:j.bool,count:j.number,large:j.bool,onClick:j.func.isRequired,starLabels:j.array},getDefaultProps:function(){return {allowMultipleSubmissions:false,count:0,large:false,starLabels:[i._("Poor"),i._("Fair"),i._("Good"),i._("Very Good"),i._("Excellent")]};},getInitialState:function(){return {starRating:this.props.count,starsShown:this.props.count,canUpdate:true};},onMouseEnter:function(l,event){if(this.state.canUpdate)this.setState({starsShown:l});},onMouseLeave:function(l,event){if(this.state.canUpdate){var m=this.state.starRating;this.setState({starsShown:m});}},onClick:function(l,event){if(this.state.canUpdate){this.setState({starRating:l,starsShown:l,canUpdate:this.props.allowMultipleSubmissions});this.props.onClick(l);}},getStars:function(){var l=this.props.starLabels.length,m=[];for(var n=0;n<l;n++){var o=n+1;m.push(c('React').createElement(c('TooltipLink.react'),{className:"mls"+(' '+"_22mm")+(this.props.large?' '+"_1vr2":'')+(n>=this.state.starsShown?' '+"_22mn":'')+(n<this.state.starsShown?' '+"_22mo":'')+(!this.state.canUpdate?' '+"_1g87":''),key:n,tooltip:this.props.starLabels[n],onMouseEnter:this.onMouseEnter.bind(this,o),onMouseLeave:this.onMouseLeave.bind(this,o),onClick:this.onClick.bind(this,o),position:'above',alignH:'center'}));}return m;},render:function(){return (c('React').createElement('div',{className:this.props.className},this.getStars()));}});f.exports=k;},null);
__d('XUIOverlayButton.react',['cx','AbstractButton.react','React','joinClasses'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();var i=c('React').createClass({displayName:'XUIOverlayButton',render:function(){var j="_51tl selected";return (c('React').createElement(c('AbstractButton.react'),babelHelpers['extends']({},this.props,{className:c('joinClasses')(this.props.className,j)})));}});f.exports=i;},null);
__d('FBRTCDialogFooter.react',['MessengerDialogFooter.react','XUIDialogFooter.react','FBRTCConfig'],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();f.exports=c('FBRTCConfig').isMessengerDotCom()?c('MessengerDialogFooter.react'):c('XUIDialogFooter.react');},null);
__d("XCollabCallSendMessageController",["XController"],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports=c("XController").create("\/collab\/sendmessage\/",{recipient_id:{type:"Int",required:true},msg_id:{type:"Int",required:true},message_info:{type:"String",required:true},webrtc_fbtrace:{type:"Int"}});},null);
__d("XLinkshimLinkAsyncController",["XController"],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports=c("XController").create("\/linkshim\/ajax\/link\/",{href:{type:"String",required:true},callsite:{type:"Enum",required:true,enumType:0}});},null);
__d("XVideoCallAdminMessageController",["XController"],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports=c("XController").create("\/videocall\/admin_msg\/",{});},null);